#!/usr/bin/env bash

#PICTURE=/tmp/i3lock.png
#SCREENSHOT="scrot -z $PICTURE"
LOCK_PICTURE=~/.config/i3/scripts/lock.png
BLUR="5x4"

#$SCREENSHOT
#convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $LOCK_PICTURE
#rm $PICTURE
